changesetBaseRefs:
  - master
  - origin/master
  - upstream/master

compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

nodeLinker: node-modules

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
