changesetBaseRefs:
  - master
  - origin/master
  - upstream/master

nodeLinker: node-modules

packageExtensions:
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
